services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_URL: ${DB_URL}
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service:
    build: .
    ports:
      - "8084:8084"
    depends_on:
      - postgres


volumes:
  postgres_data: {}