services:
  auth-app:
    build:
      context: .
    container_name: auth_service
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - postgres
    networks:
      - auth_net
    env_file:
      - .env

  postgres:
      image: postgres:16
      restart: always
      container_name: auth_db
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: ${DB_LOGIN}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_URL: ${DB_URL}
      networks:
        - auth_net
      volumes:
        - postgres_data:/var/lib/postgresql/data

networks:
  auth_net:
    driver: bridge

volumes:
  postgres_data: {}