spring.datasource.url=jdbc:postgresql://localhost:5432/authDB
spring.datasource.username=postgres
spring.datasource.password=root

server.port = 8081

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

security.token.signing.key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
security.jwt.access_token_expiration: 36000000
security.jwt.refresh_token_expiration: 252000000